### ISSUE TITLE
Conflict with ControlNet.

### ISSUE THREAD

**Issue by player99963** [ArtVentureX/sd-webui-agent-scheduler#173]
Yesterday, all the scheduling generation failed, and it is confirmed that there is a conflict with ControlNet.

![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/36121614/e163ecbe-3336-4307-8143-3c1858c7a4c1)

Loading VAE weights specified in settings: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\VAE\mastervae_v1Safetensors.safetensors

Applying attention optimization: sdp... done.

Model loaded in 7.5s (load weights from disk: 1.2s, create model: 0.4s, apply weights to model: 4.8s, load VAE: 0.4s, load textual inversion embeddings: 0.3s, calculate empty prompt: 0.2s).

*** Error completing request

*** Arguments: ('task(ca573n7a191hwol)', '', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', ['Clip skip: 2', 'Model hash: corneos7thHeavenMix_v2.safetensors [7ffbd01916]', 'VAE: mastervae_v1Safetensors.safetensors'], <agent_scheduler.task_runner.FakeRequest object at 0x0000020F79006200>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, {'is_cnet': True, 'enabled': False, 'module': 'none', 'model': 'None', 'weight': 1, 'image': None, 'resize_mode': 'Crop and Resize', 'low_vram': False, 'processor_res': -1, 'threshold_a': -1, 'threshold_b': -1, 'guidance_start': 0, 'guidance_end': 1, 'pixel_perfect': False, 'control_mode': 'Balanced', 'save_detected_map': True, 'is_ui': True, 'input_mode': 'simple', 'batch_images': '', 'output_dir': '', 'loopback': False}, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, 50) {}

Traceback (most recent call last):

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\call_queue.py", line 57, in f

res = list(func(*args, **kwargs))

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img

processed = processing.process_images(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\processing.py", line 732, in process_images

res = process_images_inner(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack

cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches

units = external_code.get_all_units_in_processing(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 191, in get_all_units_in_processing

return get_all_units(p.scripts, p.script_args)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 202, in get_all_units

return get_all_units_from(script_args[cn_script.args_from:cn_script.args_to])

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 233, in get_all_units_from

all_units = [

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 234, in <listcomp>

to_processing_unit(script_arg)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 307, in to_processing_unit

unit = ControlNetUnit(**unit)

TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'is_cnet'

---

ERROR:sd:[AgentScheduler] Task task(ca573n7a191hwol) failed:

**Comment by LEONLAURA** [comment]
i am the same as yours

**Comment by broszkiet** [comment]
same problem

**Comment by afbagwell** [comment]
Seeing the same issue on SDNext.

```
10:12:32-089647 INFO     Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)
                         Gecko/20100101 Firefox/119.0
10:16:41-469508 INFO     [AgentScheduler] Total pending tasks: 1
10:16:41-471555 INFO     [AgentScheduler] Executing task task(rc91ovcxwrh1mg6)
10:16:41-473742 ERROR    gradio call: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/afbag/sdnext/modules/call_queue.py:57 in f                                                                     │
│                                                                                                                      │
│   56 │   │   │   │   pr.enable()                                                                                     │
│ ❱ 57 │   │   │   res = func(*args, **kwargs)                                                                         │
│   58 │   │   │   if res is None:                                                                                     │
│                                                                                                                      │
│ /home/afbag/sdnext/modules/txt2img.py:66 in txt2img                                                                  │
│                                                                                                                      │
│   65 │   if processed is None:                                                                                       │
│ ❱ 66 │   │   processed = processing.process_images(p)                                                                │
│   67 │   p.close()                                                                                                   │
│                                                                                                                      │
│ /home/afbag/sdnext/modules/processing.py:742 in process_images                                                       │
│                                                                                                                      │
│    741 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                         │
│ ❱  742 │   │   │   │   res = process_images_inner(p)                                                                 │
│    743 │   finally:                                                                                                  │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/scripts/batch_hijack.py:39 in                              │
│ processing_process_images_hijack                                                                                     │
│                                                                                                                      │
│    38 │   │                                                                                                          │
│ ❱  39 │   │   cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)                                 │
│    40 │   │   if not cn_is_batch:                                                                                    │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/scripts/batch_hijack.py:184 in get_cn_batches              │
│                                                                                                                      │
│   183 def get_cn_batches(p: processing.StableDiffusionProcessing) -> Tuple[bool, List[List[str                       │
│ ❱ 184 │   units = external_code.get_all_units_in_processing(p)                                                       │
│   185 │   units = [copy(unit) for unit in units if getattr(unit, 'enabled', False)]                                  │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py:191 in                │
│ get_all_units_in_processing                                                                                          │
│                                                                                                                      │
│   190 │                                                                                                              │
│ ❱ 191 │   return get_all_units(p.scripts, p.script_args)                                                             │
│   192                                                                                                                │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py:202 in get_all_units  │
│                                                                                                                      │
│   201 │   if cn_script:                                                                                              │
│ ❱ 202 │   │   return get_all_units_from(script_args[cn_script.args_from:cn_script.args_to])                          │
│   203                                                                                                                │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py:233 in                │
│ get_all_units_from                                                                                                   │
│                                                                                                                      │
│   232 │                                                                                                              │
│ ❱ 233 │   all_units = [                                                                                              │
│   234 │   │   to_processing_unit(script_arg)                                                                         │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py:234 in <listcomp>     │
│                                                                                                                      │
│   233 │   all_units = [                                                                                              │
│ ❱ 234 │   │   to_processing_unit(script_arg)                                                                         │
│   235 │   │   for script_arg in script_args                                                                          │
│                                                                                                                      │
│ /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py:307 in                │
│ to_processing_unit                                                                                                   │
│                                                                                                                      │
│   306 │   │                                                                                                          │
│ ❱ 307 │   │   unit = ControlNetUnit(**unit)                                                                          │
│   308                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'is_cnet'
10:16:41-574247 ERROR    [AgentScheduler] Task task(rc91ovcxwrh1mg6) failed:
10:16:41-579818 INFO     [AgentScheduler] Task queue is empty
```

**Comment by artventuredev** [comment]
I'm looking into it.

**Comment by artventuredev** [comment]
The issue should be fixed with the latest commit, please update and give it a try.

**Comment by afbagwell** [comment]
Working now in SDNext!

**Comment by player99963** [comment]
Works properly in A1111.

**Comment by player99963** [comment]
Error still occurs when using ControlNet in i2i

*** Error completing request

*** Arguments: ('task(vvf1lezk61em9fu)', 0, '1girl,', '(badv5:1.1),(badhandv4:1.1),(verybadimagenegative_v1.3:1.1),(crown:1.8),(nose:1.5),(realistic:1.5),(photorealistic:1.5),(flower:1.5),(text:1.4),', [], <PIL.Image.Image image mode=RGBA size=688x1024 at 0x124816B2590>, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 3, 1.5, 0.5, 0, 1024, 688, 1, 0, 0, 32, 0, '', '', '', ['Clip skip: 2', 'Model hash: corneos7thHeavenMix_v2.safetensors [7ffbd01916]', 'VAE: mastervae_v1Safetensors.safetensors'], False, [], '', <agent_scheduler.task_runner.FakeRequest object at 0x00000124816B2710>, 0, False, '', 0.8, 4043955090, False, -1, 0, 0, 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'SwinIR_4x', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', UiControlNetUnit(enabled=True, module='tile_resample', model='control_v11f1e_sd15_tile [a371b31b]', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=True, control_mode='ControlNet is more important', save_detected_map=True), False, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, '* CFG Scale should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', 0, '', None, None, False, 50) {}

Traceback (most recent call last):

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\call_queue.py", line 57, in f

res = list(func(*args, **kwargs))

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\img2img.py", line 208, in img2img

processed = process_images(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\processing.py", line 732, in process_images

res = process_images_inner(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack

cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)

File "D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 210, in get_cn_batches

batches[i].append(unit.batch_images[i])

IndexError: string index out of range

---

ERROR:sd:[AgentScheduler] Task task(vvf1lezk61em9fu) failed:

**Comment by artventuredev** [comment]
@player99963 I've just pushed a new update, please update and try again.

**Comment by player99963** [comment]
It worked. Thank you.
